name: CML test 1
# Controls when the workflow will run
on: [push]
jobs:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v3
      - name: Model building
      - run: |
          pip install -r requirements.txt
          python train.py
          
          echo "##Model Matrics" > report.md
          cat matrics.txt >> report.md
          
          echo "## Data Viz" >> report.md
          
          cml publish feature_importance.png --md >> report.md
          cml publish residuals.png --md >> report.md
          
          cml-send-comment report.md
          
          
